### PR TITLE
Updated camp information and added committee.

### PR DESCRIPTION
**Pull request by parndt**
Please, quibble.

### CODE REVIEW

**Comment by patrickdavey** [comment]
What do you think about having twitter handles linked on the committee page?  (and maybe also links to the regional twitter handles too (@chchruby etc.)

**Comment by parndt** [comment]
I feel favourably about that, as long as everyone else agrees to their Twitter handle being added.

**Comment by danielfone** [comment]
@parndt :+1:

**Comment by jimsynz** [comment]
Fine by me.

**Comment by megahbite** [comment]
Yup, fine by me too. Will add one of those silly disclaimers about my views not representing RubyNZ so there can be no room for misunderstanding.

**Comment by awagener** [comment]
:+1:

**Comment by awagener** [comment]
I think it's good to have a way for our 'constituents' to reach us.  :smile:

**Comment by Aupajo** [comment]
:+1:

**Comment by eoinkelly** [comment]
:+1:

**Comment by parndt** [comment]
@nzruby/committee okay can everyone please edit their Twitter handle on to [this branch](https://github.com/nzruby/www/blob/added-committee/index.html)?

**Comment by megahbite** [comment]
That's everyone @parndt

**Comment by parndt** [comment]
Democracy!

**Pull request merged**
