### PR TITLE
Remove obsolete membership page

### PR DESCRIPTION
**Pull request by mermop**
I believe this page has been superseded by membership.ruby.nz - @danielfone can you confirm?

<details>
<summary>Screenshot</summary>
Screen Shot 2019-04-13 at 12 24 25 PM
</details>

### CODE REVIEW

**Review by Aupajo — APPROVED** [review]

**Comment by Aupajo** [comment]
@mermop Do we need to remove any inbound links to this, or set up a redirect to the new page?

**Comment by mermop** [comment]
I don't thiiiiink there's any inbound links, but a redirect couldn't hurt

**Comment by mermop** [comment]
@Aupajo do you want to have another look over before I merge - I've explicitly added jekyll so that the redirection plugin works

**Review by Aupajo — APPROVED** [review]

**Comment by Aupajo** [comment]
@mermop Looks good to me!

**Comment by danielfone** [comment]
@mermop I can confirm

**Pull request merged**
