### PR TITLE
Add a register of ruby companies page

### PR DESCRIPTION
**Pull request by libbyschuknight**
Awhile ago in Slack channel there was discussion around this - Companies page #10.

This PR takes the `resolve:register_of_ruby_companies` branch and updates it to be inline with the styling changes made to the site. 

Changes made:
- add "Companies" to left hand list of index page
- add "Companies" section to the bottom of the index page
- add "Companies" page, ruby icon and ruby nz text link back to home page

Note: first time I have forked anything and made a PR from it 😜.

<details>
<summary>Couple of Screenshots</summary>
screen shot 2017-08-13 at 5 16 38 pm

screen shot 2017-08-13 at 5 19 44 pm

</details>

### CODE REVIEW

**Review by danielfone — COMMENTED** [review]
Great job thanks Libby! My only thought is that (ironically) Resolve is no longer around. Once that's removed then LGTM.

**Comment by raquelxmoss** [comment]
I'm also not sure that 3months are primarily a Ruby shop these days -- they pivoted to more blockchain stuff 🤔. Might want to remove them, or get in touch with Mark Pascall and see if they want to be included.

**Comment by libbyschuknight** [comment]
Yeah, I was wondering about some of the companies, as I'm not sure Southgate Labs is a thing any more. There site works - http://southgatelabs.com/ - but there doesn't seem to be a way to contact anyone.

**Comment by danielfone** [comment]
I think this highlights one of the difficulties of a page like this: it can become stale quite quickly and it's difficult to know who'll maintain it. I haven't read the recent discussion in slack, but I believe this is part of the reason the original PR wasn't merged.

**Comment by megahbite** [comment]
I would also be concerned about it looking like Ruby NZ is endorsing these companies. I would suggest, if this goes aheads, some language around this being a user submitted list and no assurances about the quality of service are given.

I'd also worry about things like what metrics decide the order of the companies and what the aim of this page is? Is it advertising for these companies?

**Pull request closed without merging**
